gui:
  theme:
    userDefinedColors:
      primary:
        text: "#f5e0dc"
        background: "#4b4b4b"
      selectedLine:
        text: "#e0def4"
        background: "#595959"
      activeBorder:
        text: "#9ccfd8"
      inactiveBorder:
        text: "#949494"
      warning:
        text: "#e81050"
        background: "#595959"
